# Generated by Django 5.0.6 on 2024-06-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
